=== bustaa/1-DAM/LDM/XSD/Tarea 2.3/actividad3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="pedido">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="empleadoresponsable"/>
                <xs:element name="enviar_a">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nomcliente" type="xs:string"/>
                            <xs:element name="direccion" type="xs:string"/>
                            <xs:element name="ciudad" type="xs:string"/>
                            <xs:element name="pais" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="producto" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titulo" type="xs:string"/>
                            <xs:element name="nota" type="xs:string" minOccurs="0"/>
                            <xs:element name="cantidad" type="xs:int"/>
                            <xs:element name="precio" type="xs:float"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="numpedido" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== bustaa/1-DAM/LDM/XSD/Tarea 2.3/actividad3.xml
<?xml version="1.0" encoding="UTF-8"?>
<pedido numpedido="889923" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="actividad3.xsd">
    <empleadoresponsable>Pepe López</empleadoresponsable>
    <enviar_a>
        <nomcliente>Ana García</nomcliente>
        <direccion>C/ Mayor, 5</direccion>
        <ciudad>46470 Catarroja</ciudad>
        <pais>España</pais>
    </enviar_a>
    <producto>
        <titulo>El Quijote</titulo>
        <nota>Edición especial</nota>
        <cantidad>1</cantidad>
        <precio>15.90</precio>
    </producto>
    <producto>
        <titulo>Misión Imposible</titulo>
        <cantidad>1</cantidad>
        <precio>9.90</precio>
    </producto>
</pedido>
