=== bustaa/1-DAM/LDM/XSD/Tarea 2.2/actividad2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="vehiculos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="vehiculo" minOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
                            <xs:element name="modelo" type="xs:string" maxOccurs="1"/>
                            <xs:element name="datos_reparacion" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="inicio" maxOccurs="1">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="dia" type="xs:string" maxOccurs="1"/>
                                                    <xs:element name="mes" type="xs:string" maxOccurs="1"/>
                                                    <xs:element name="anyo" type="xs:string" maxOccurs="1"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="fin" maxOccurs="1">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="dia" type="xs:string" maxOccurs="1"/>
                                                    <xs:element name="mes" type="xs:string" maxOccurs="1"/>
                                                    <xs:element name="anyo" type="xs:string" maxOccurs="1"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="reparaciones" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="reparacion" type="xs:string" minOccurs="1"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== bustaa/1-DAM/LDM/XSD/Tarea 2.2/actividad2.xml
<?xml version="1.0" encoding="UTF-8"?>
<vehiculos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="actividad2.xsd">
    <vehiculo>
        <nombre>Seat Ibiza</nombre>
        <modelo>1800 5 puertas</modelo>
        <datos_reparacion>
            <inicio>
                <dia>12</dia>
                <mes>Mayo</mes>
                <anyo>2018</anyo>
            </inicio>
            <fin>
                <dia>16</dia>
                <mes>mayo</mes>
                <anyo>2018</anyo>
            </fin>
        </datos_reparacion>
        <reparaciones>
            <reparacion>Cambio aceite</reparacion>
            <reparacion>Cambio de ruedas</reparacion>
            <reparacion>Revisi√≥n sistema frenado</reparacion>
            <reparacion>Pintar</reparacion>
        </reparaciones>
    </vehiculo>
</vehiculos>
