=== bustaa/1-DAM/LDM/XSD/Tarea 2.6/bibliotecaLibros.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="libros">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="libro" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="autor" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
                            <xs:element name="f_publicacion" minOccurs="1" maxOccurs="1">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="0"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="titulo" type="xs:string" minOccurs="1" maxOccurs="1"/>
                            <xs:element name="pags" minOccurs="1" maxOccurs="1">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="0"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="editorial" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== bustaa/1-DAM/LDM/XSD/Tarea 2.6/bibliotecaLibros.xml
<?xml version="1.0" encoding="UTF-8"?>
<libros xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="bibliotecaLibros.xsd">
    <libro>
        <autor>Carlos Ruíz Zafín</autor>
        <f_publicacion>2002</f_publicacion>
        <titulo>La sombra del viento</titulo>
        <pags>565</pags>
        <editorial>Editorial Planeta</editorial>
    </libro>
    <libro>
        <autor>María Dueñas</autor>
        <f_publicacion>2010</f_publicacion>
        <titulo>El tiempo entre costuras</titulo>
        <pags>640</pags>
        <editorial>Editorial Planeta</editorial>
    </libro>
    <libro>
        <autor>Arturo Pérez Reverte</autor>
        <f_publicacion>2010</f_publicacion>
        <titulo>El asedio</titulo>
        <pags>736</pags>
        <editorial>Editorial Alfaguara</editorial>
    </libro>
</libros>
