=== bustaa/1-DAM/LDM/XSD/Tarea 2.5/sociosClub.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="socios">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="socio" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string" minOccurs="1" maxOccurs="1"/>
                            <xs:element name="antiguedad" minOccurs="1" maxOccurs="1">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="0"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="poblacion" type="xs:string" minOccurs="1" maxOccurs="1"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== bustaa/1-DAM/LDM/XSD/Tarea 2.5/sociosClub.xml
<?xml version="1.0" encoding="UTF-8"?>
<socios xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="sociosClub.xsd">
    <socio>
        <nombre>Pepe</nombre>
        <antiguedad>4</antiguedad>
        <poblacion>Catarroja</poblacion>
    </socio>
    <socio>
        <nombre>Ana</nombre>
        <antiguedad>5</antiguedad>
        <poblacion>Albal</poblacion>
    </socio>
    <socio>
        <nombre>Juan</nombre>
        <antiguedad>3</antiguedad>
        <poblacion>Catarroja</poblacion>
    </socio>
</socios>
